import { pgTable, serial, varchar, char, timestamp, real, smallint, integer } from 'drizzle-orm/pg-core'
import { responsavel } from './responsavel'

// OBRA - Tabela principal de obras
export const obra = pgTable('OBRA', {
  idObra: serial('ID_OBRA').primaryKey(),
  idAlvara: varchar('ID_ALVARA', { length: 15 }),
  dtAlvara: timestamp('DT_ALVARA'),
  nmObra: varchar('NM_OBRA', { length: 55 }),
  idTipoLgdr: varchar('ID_TIPO_LGDR', { length: 10 }),
  nmEndereco: varchar('NM_ENDERECO', { length: 55 }),
  nuEndereco: varchar('NU_ENDERECO', { length: 10 }).default(''),
  complEndereco: varchar('COMPL_ENDERECO', { length: 10 }).default(''),
  nmBairro: varchar('NM_BAIRRO', { length: 20 }),
  nuCep: varchar('NU_CEP', { length: 8 }),
  idMunicipio: varchar('ID_MUNICIPIO', { length: 6 }),
  nmCidade: varchar('NM_CIDADE', { length: 30 }),
  csUf: char('CS_UF', { length: 2 }),
  teEmail: varchar('TE_EMAIL', { length: 60 }),
  idTipoLgdrCorr: varchar('ID_TIPO_LGDR_CORR', { length: 10 }),
  nmEnderecoCorr: varchar('NM_ENDERECO_CORR', { length: 55 }),
  nuEnderecoCorr: varchar('NU_ENDERECO_CORR', { length: 10 }).default(''),
  nmBairroCorr: varchar('NM_BAIRRO_CORR', { length: 20 }),
  complEnderecoCorr: varchar('COMPL_ENDERECO_CORR', { length: 10 }).default(''),
  nuCepCorr: varchar('NU_CEP_CORR', { length: 8 }),
  idMunicipioCorr: varchar('ID_MUNICIPIO_CORR', { length: 6 }),
  nuTelefone: varchar('NU_TELEFONE', { length: 14 }),
  nuFax: varchar('NU_FAX', { length: 14 }),
  dtAtualizacao: timestamp('DT_ATUALIZACAO'),
  inTransmitido: varchar('IN_TRANSMITIDO', { length: 1 }),
  dtTransmissao: timestamp('DT_TRANSMISSAO'),
  csTipoTx: varchar('CS_TIPO_TX', { length: 1 }),
  csSituacao: varchar('CS_SITUACAO', { length: 70 }),
  csClasse: varchar('CS_CLASSE', { length: 10 }),
  idAlvaraAnterior: varchar('ID_ALVARA_ANTERIOR', { length: 15 }),
  dtInicio: timestamp('DT_INICIO'),
  dtFim: timestamp('DT_FIM'),
  nuArtProjeto: varchar('NU_ART_PROJETO', { length: 20 }),
  nuArtObra: varchar('NU_ART_OBRA', { length: 20 }),
  nmEngenheiro: varchar('NM_ENGENHEIRO', { length: 55 }),
  nuIndFiscal: varchar('NU_IND_FISCAL', { length: 15 }),
  nuProcesso: varchar('NU_PROCESSO', { length: 25 }),
  txEspecObra: varchar('TX_ESPEC_OBRA', { length: 4096 }),
  txObs: varchar('TX_OBS', { length: 4096 }),
  csUfCorr: char('CS_UF_CORR', { length: 2 }),
  csTipRespSol: char('CS_TIP_RESP_SOL', { length: 1 }),
  idResponsavelSol: varchar('ID_RESPONSAVEL_SOL', { length: 14 }),
  nmResponsavelSol: varchar('NM_RESPONSAVEL_SOL', { length: 55 }),
  idTipoLgdrSol: varchar('ID_TIPO_LGDR_SOL', { length: 10 }),
  nmEnderecoSol: varchar('NM_ENDERECO_SOL', { length: 55 }),
  nuEnderecoSol: varchar('NU_ENDERECO_SOL', { length: 10 }),
  complEnderecoSol: varchar('COMPL_ENDERECO_SOL', { length: 10 }),
  nmBairroSol: varchar('NM_BAIRRO_SOL', { length: 20 }),
  nuCepSol: varchar('NU_CEP_SOL', { length: 8 }),
  idMunicipioSol: varchar('ID_MUNICIPIO_SOL', { length: 6 }),
  nmCidadeSol: varchar('NM_CIDADE_SOL', { length: 30 }),
  csUfSol: char('CS_UF_SOL', { length: 2 }),
  csTipOcupConstr: char('CS_TIP_OCUP_CONSTR', { length: 1 }).default(' ').notNull(),
  csTipConstrConstr: char('CS_TIP_CONSTR_CONSTR', { length: 1 }).default(' ').notNull(),
  vlAreaConstr: real('VL_AREA_CONSTR'),
  csTipOcupDemol: char('CS_TIP_OCUP_DEMOL', { length: 1 }).default(' ').notNull(),
  csTipConstrDemol: char('CS_TIP_CONSTR_DEMOL', { length: 1 }).default(' ').notNull(),
  vlAreaDemol: real('VL_AREA_DEMOL'),
  csTipOcupAcres: char('CS_TIP_OCUP_ACRES', { length: 1 }).default(' ').notNull(),
  csTipConstrAcres: char('CS_TIP_CONSTR_ACRES', { length: 1 }).default(' ').notNull(),
  vlAreaAcres: real('VL_AREA_ACRES'),
  vlAreaExistente: real('VL_AREA_EXISTENTE'),
  csTipOcupRefor: char('CS_TIP_OCUP_REFOR', { length: 1 }).default(' ').notNull(),
  csTipConstrRefor: char('CS_TIP_CONSTR_REFOR', { length: 1 }).default(' ').notNull(),
  vlAreaRefor: real('VL_AREA_REFOR'),
  nmEngenheiroProj: varchar('NM_ENGENHEIRO_PROJ', { length: 55 }),
  creaEngenheiro: varchar('CREA_ENGENHEIRO', { length: 20 }),
  creaEngenheiroProj: varchar('CREA_ENGENHEIRO_PROJ', { length: 20 }),
  usuario: varchar('USUARIO', { length: 8 }),
  dtEmissaoAlvara: timestamp('DT_EMISSAO_ALVARA'),
  nuPavimento: smallint('NU_PAVIMENTO'),
  nuUnidade: smallint('NU_UNIDADE'),
  nuDddTel: varchar('NU_DDD_TEL', { length: 4 }),
  nuDddFax: varchar('NU_DDD_FAX', { length: 4 }),
})

// VINCULO - Relacionamento entre responsável e obra
export const vinculo = pgTable('VINCULO', {
  idResponsavel: varchar('ID_RESPONSAVEL', { length: 14 }).notNull().references(() => responsavel.idResponsavel),
  idObra: integer('ID_OBRA').notNull().references(() => obra.idObra, { onDelete: 'cascade' }),
  csTipoResponsavel: char('CS_TIPO_RESPONSAVEL', { length: 1 }),
  dtInicioPeriodo: timestamp('DT_INICIO_PERIODO').notNull(),
  dtFimPeriodo: timestamp('DT_FIM_PERIODO'),
  tpQualificInss: varchar('TP_QUALIFIC_INSS', { length: 2 }).notNull(),
  dtAtualizacao: timestamp('DT_ATUALIZACAO'),
  seqVinc: smallint('SEQ_VINC'),
  inTransmitido: varchar('IN_TRANSMITIDO', { length: 1 }),
})

// HABITESE - Habite-se das obras
export const habitese = pgTable('HABITESE', {
  idHabitese: varchar('ID_HABITESE', { length: 15 }),
  dtHabitese: timestamp('DT_HABITESE'),
  idObra: integer('ID_OBRA').references(() => obra.idObra, { onDelete: 'cascade' }),
  area: real('AREA'),
  sequencialHabitese: smallint('SEQUENCIAL_HABITESE').notNull(),
  csTipHabitese: varchar('CS_TIP_HABITESE', { length: 1 }).default('P').notNull(),
  usuarioHabitese: varchar('USUARIO_HABITESE', { length: 8 }),
  dtEmissaoHabitese: timestamp('DT_EMISSAO_HABITESE'),
  txObs: varchar('TX_OBS', { length: 4096 }),
})