import { pgTable, varchar, char, timestamp } from 'drizzle-orm/pg-core'

// RESPONSAVEL - usando nomes em minúsculo
export const responsavel = pgTable('responsavel', {
  csTipResp: char('cs_tip_resp', { length: 1 }),
  idResponsavel: varchar('id_responsavel', { length: 14 }).primaryKey(),
  nmResponsavel: varchar('nm_responsavel', { length: 55 }),
  idTipoLgdr: varchar('id_tipo_lgdr', { length: 10 }),
  nmEndereco: varchar('nm_endereco', { length: 55 }),
  nuEndereco: varchar('nu_endereco', { length: 10 }).default(''),
  complEndereco: varchar('compl_endereco', { length: 10 }).default(''),
  nmBairro: varchar('nm_bairro', { length: 20 }),
  nuCep: varchar('nu_cep', { length: 8 }),
  idMunicipio: varchar('id_municipio', { length: 6 }),
  nmCidade: varchar('nm_cidade', { length: 30 }),
  csUf: char('cs_uf', { length: 2 }),
  idTipoLgdrCorr: varchar('id_tipo_lgdr_corr', { length: 10 }),
  nmEnderecoCorr: varchar('nm_endereco_corr', { length: 55 }),
  nuEnderecoCorr: varchar('nu_endereco_corr', { length: 10 }).default(''),
  complEnderecoCorr: varchar('compl_endereco_corr', { length: 10 }).default(''),
  nmBairroCorr: varchar('nm_bairro_corr', { length: 20 }),
  nuCepCorr: varchar('nu_cep_corr', { length: 8 }),
  idMunicipioCorr: varchar('id_municipio_corr', { length: 6 }),
  nmCidadeCorr: varchar('nm_cidade_corr', { length: 30 }),
  nuTelefone: varchar('nu_telefone', { length: 14 }),
  nuFax: varchar('nu_fax', { length: 14 }),
  teEmail: varchar('te_email', { length: 60 }),
  dtAtualizacao: timestamp('dt_atualizacao'),
  csUfCorr: char('cs_uf_corr', { length: 2 }),
  nuDddTel: varchar('nu_ddd_tel', { length: 4 }),
  nuDddFax: varchar('nu_ddd_fax', { length: 4 }),
})